name = "QXTn"
uuid = "995e1dad-72e3-4b97-b122-7deaeb8b44f9"
authors = ["QuantEx team"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NDTensors = "23ae76d9-e61a-49c4-8f12-3f1a16adf9cf"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
DataStructures = "0.18"
ITensors = "0.1"
NDTensors = "0.1"
TestSetExtensions = "2.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
